# Generated by Django 5.2.13 on 2026-04-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracker_app', '0002_alter_invoice_due_date_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
    ]
